### ISSUE TITLE
Change app name and icon

### ISSUE THREAD

**Issue by kubil-ismail** [MuhammadSonySetiawan/pijar-food-rn-fe#2]
![WhatsApp Image 2023-08-07 at 21 04 53](https://github.com/MuhammadSonySetiawan/pijar-food-rn-fe/assets/49361887/bd942a30-8ea0-47ed-b50a-6d29e5e2fce0)

**Comment by MuhammadSonySetiawan** [comment]
Change app name and icon
![Screenshot 2023-08-08 110447](https://github.com/MuhammadSonySetiawan/pijar-food-mobile/assets/132990489/86de90a3-5045-4a33-a234-ab3228659e9d)
