### ISSUE TITLE
Centered button

### ISSUE THREAD

**Issue by kubil-ismail** [MuhammadSonySetiawan/pijar-food-rn-fe#3]
![WhatsApp Image 2023-08-07 at 21 06 33](https://github.com/MuhammadSonySetiawan/pijar-food-rn-fe/assets/49361887/64cb4ecd-ba48-4d27-b6b4-1a2b6feb4838)

Please fix layout button to centered

**Comment by MuhammadSonySetiawan** [comment]
fixing button layout to center
![Screenshot 2023-08-08 011446](https://github.com/MuhammadSonySetiawan/pijar-food-mobile/assets/132990489/2ac6a8c8-24a9-4f3f-a512-b1b0775cf88e)
