### ISSUE TITLE
fix navigation text in auth page

### ISSUE THREAD

**Issue by kubil-ismail** [MuhammadSonySetiawan/pijar-food-rn-fe#4]
![WhatsApp Image 2023-08-07 at 21 08 31](https://github.com/MuhammadSonySetiawan/pijar-food-rn-fe/assets/49361887/4aef25c6-bf15-440a-9e96-212f569931a5)
![WhatsApp Image 2023-08-07 at 21 08 30](https://github.com/MuhammadSonySetiawan/pijar-food-rn-fe/assets/49361887/40c6f71d-bf3b-4d04-81f0-6b3b5a0411b0)

**Comment by MuhammadSonySetiawan** [comment]
fixing position  text navigation in auth page
![Screenshot 2023-08-08 012041](https://github.com/MuhammadSonySetiawan/pijar-food-mobile/assets/132990489/64eb36ae-ba06-4e31-ab1e-92ae32577cf8)
![Screenshot 2023-08-08 012230](https://github.com/MuhammadSonySetiawan/pijar-food-mobile/assets/132990489/b934c637-6042-494c-b7cc-d8c08a21fd12)
