### ISSUE TITLE
Detail recipe wrong

### ISSUE THREAD

**Issue by kubil-ismail** [MuhammadSonySetiawan/pijar-food-rn-fe#7]
If i click detail not showing what recipe i clicked, please fix that

**Comment by MuhammadSonySetiawan** [comment]
The recipe detail page is integrated and shows what has been clicked from the home page
![Screenshot 2023-08-08 013428](https://github.com/MuhammadSonySetiawan/pijar-food-mobile/assets/132990489/a8282e85-156b-43ca-8f07-802425aff359)
