### ISSUE TITLE
Fix profile layout

### ISSUE THREAD

**Issue by kubil-ismail** [MuhammadSonySetiawan/pijar-food-rn-fe#9]
![WhatsApp Image 2023-08-07 at 21 13 15](https://github.com/MuhammadSonySetiawan/pijar-food-rn-fe/assets/49361887/4ba4d077-a183-4186-82d5-573261c1e2f9)

**Comment by MuhammadSonySetiawan** [comment]
Fixing integrasi profile
![Screenshot 2023-08-08 013159](https://github.com/MuhammadSonySetiawan/pijar-food-mobile/assets/132990489/7a3c6197-6e26-484d-b8a5-94321ac00c3e)

**Comment by kubil-ismail** [comment]
Still happen in device android oppo

**Comment by kubil-ismail** [comment]
Please add logout feature to

**Comment by MuhammadSonySetiawan** [comment]
fixed display issues on some devices and Added logout button
![WhatsApp Image 2023-08-14 at 10 10 49](https://github.com/MuhammadSonySetiawan/pijar-food-mobile/assets/132990489/c780200e-79cd-4e1e-bf33-91a6d4b984ed)
